# Generated by Django 4.0.6 on 2022-12-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=15)),
                ('release_data', models.CharField(max_length=20)),
                ('lte_exist', models.CharField(max_length=5)),
                ('slug', models.CharField(max_length=20)),
            ],
        ),
    ]
