# Generated by Django 4.0.6 on 2022-12-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='img',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
